#!/bin/bash
#
# Author:   Mac Deluca
# Date:     30-03-24
# Purpose:  Script to display docker container logs with fzf.
#

# Use fzf to pick a running container
CONTAINER=$(docker ps --all --format 'json' | jq -r '.Names' | fzf --preview "docker logs {} --follow --tail 500")

# output the logs to terminal
docker logs $CONTAINER --follow --tail 500
