#!/bin/bash

tmux has-session -t $1 2>/dev/null
has_session=$?

if [ $has_session != 0 ]; then
  tmux new-session -s "$1" -d

  if [ $1 == "term" ]; then
    cd ~/projects/

    tmux split-window -h
    tmux split-window -h
    tmux split-window -h
    tmux select-layout tiled

  elif [ $1 == "bctw-api" ]; then
    tmux send-keys "cd ~/projects/bctw-api/bctw-api/ && vim . && clear" Enter

  elif [ $1 == "critterbase" ]; then
    tmux send-keys "cd ~/projects/critterbase-api/ && vim . && clear" Enter

  elif [ $1 == "sims" ]; then
    tmux send-keys "cd ~/projects/biohubbc/ && vim . && clear" Enter

  elif [ $1 == "biohub" ]; then
    tmux send-keys "cd ~/projects/biohubbc-platform/ && vim . && clear" Enter
  fi

fi

tmux attach-session -t "$1"

