#!/bin/bash
#
# Author:   Mac Deluca
# Date:     20-08-23
# Purpose:  Helper script for attaching to tmux sessions
#

selected=`echo $(tmux ls | cut -d: -f1) | pick`

if [ -z "$selected" ]; then
  >&2 echo "no session selected"

else
  tmux attach-session -t "$selected"
  echo "session: $selected"
fi

